// `mapInstructionTemps` rewrites every temp operand of one instruction, definitions included,
// with one arm per `IrInstructionKind` constructor so a kind can never be silently skipped: the
// optimizer's Borrow/RcDup elision remaps the uses of an erased temp through it, and an arm left
// out would leave a dangling operand behind for codegen to trip over. The arms are derived
// mechanically from the type declaration: every `IrTemp` field passes through `f`, a
// `List(IrTemp)` maps `f` over its elements, frame save/restore records rewrite their temp field,
// and every other field is carried unchanged. Adding a constructor to `IrInstructionKind` without
// an arm here is a compile error, which is the point.
import Ashes.Collection.List.map
import AshesCompiler.Semantics.IrInstructions
export (
    value mapInstructionTemps,
    value mapInstructionLocals,
)

let mapFrameSaveTemps f saves =
    Ashes.Collection.List.map((given (save: IrFrameSave) -> save with sourceTemp = f(save.sourceTemp)))(saves)

let mapFrameRestoreTemps f restores =
    Ashes.Collection.List.map((given (restore: IrFrameRestore) -> restore with targetTemp = f(restore.targetTemp)))(restores)

let mapInstructionTemps f (kind: IrInstructionKind) =
    match kind with
        | LoadConstInt(T0, n0) -> LoadConstInt(f(T0))(n0)
        | LoadConstFloat(T0, fl0) -> LoadConstFloat(f(T0))(fl0)
        | LoadConstBool(T0, b0) -> LoadConstBool(f(T0))(b0)
        | LoadConstStr(T0, s0) -> LoadConstStr(f(T0))(s0)
        | LoadProgramArgs(T0) -> LoadProgramArgs(f(T0))
        | LoadLocal(T0, l0) -> LoadLocal(f(T0))(l0)
        | StoreLocal(l0, T0) -> StoreLocal(l0)(f(T0))
        | LoadEnv(T0, n0) -> LoadEnv(f(T0))(n0)
        | StoreMemOffset(T0, n0, T1) -> StoreMemOffset(f(T0))(n0)(f(T1))
        | LoadMemOffset(T0, T1, n0) -> LoadMemOffset(f(T0))(f(T1))(n0)
        | AddInt(T0, T1, T2) -> AddInt(f(T0))(f(T1))(f(T2))
        | SubInt(T0, T1, T2) -> SubInt(f(T0))(f(T1))(f(T2))
        | MulInt(T0, T1, T2) -> MulInt(f(T0))(f(T1))(f(T2))
        | DivInt(T0, T1, T2) -> DivInt(f(T0))(f(T1))(f(T2))
        | DivUInt(T0, T1, T2) -> DivUInt(f(T0))(f(T1))(f(T2))
        | AndInt(T0, T1, T2) -> AndInt(f(T0))(f(T1))(f(T2))
        | OrInt(T0, T1, T2) -> OrInt(f(T0))(f(T1))(f(T2))
        | XorInt(T0, T1, T2) -> XorInt(f(T0))(f(T1))(f(T2))
        | ShlInt(T0, T1, T2) -> ShlInt(f(T0))(f(T1))(f(T2))
        | ShrInt(T0, T1, T2) -> ShrInt(f(T0))(f(T1))(f(T2))
        | AddFloat(T0, T1, T2) -> AddFloat(f(T0))(f(T1))(f(T2))
        | SubFloat(T0, T1, T2) -> SubFloat(f(T0))(f(T1))(f(T2))
        | MulFloat(T0, T1, T2) -> MulFloat(f(T0))(f(T1))(f(T2))
        | DivFloat(T0, T1, T2) -> DivFloat(f(T0))(f(T1))(f(T2))
        | CmpIntGt(T0, T1, T2) -> CmpIntGt(f(T0))(f(T1))(f(T2))
        | CmpIntGe(T0, T1, T2) -> CmpIntGe(f(T0))(f(T1))(f(T2))
        | CmpIntLt(T0, T1, T2) -> CmpIntLt(f(T0))(f(T1))(f(T2))
        | CmpIntLe(T0, T1, T2) -> CmpIntLe(f(T0))(f(T1))(f(T2))
        | CmpUIntGt(T0, T1, T2) -> CmpUIntGt(f(T0))(f(T1))(f(T2))
        | CmpUIntGe(T0, T1, T2) -> CmpUIntGe(f(T0))(f(T1))(f(T2))
        | CmpUIntLt(T0, T1, T2) -> CmpUIntLt(f(T0))(f(T1))(f(T2))
        | CmpUIntLe(T0, T1, T2) -> CmpUIntLe(f(T0))(f(T1))(f(T2))
        | CmpIntEq(T0, T1, T2) -> CmpIntEq(f(T0))(f(T1))(f(T2))
        | CmpIntNe(T0, T1, T2) -> CmpIntNe(f(T0))(f(T1))(f(T2))
        | CmpFloatGt(T0, T1, T2) -> CmpFloatGt(f(T0))(f(T1))(f(T2))
        | CmpFloatGe(T0, T1, T2) -> CmpFloatGe(f(T0))(f(T1))(f(T2))
        | CmpFloatLt(T0, T1, T2) -> CmpFloatLt(f(T0))(f(T1))(f(T2))
        | CmpFloatLe(T0, T1, T2) -> CmpFloatLe(f(T0))(f(T1))(f(T2))
        | CmpFloatEq(T0, T1, T2) -> CmpFloatEq(f(T0))(f(T1))(f(T2))
        | CmpFloatNe(T0, T1, T2) -> CmpFloatNe(f(T0))(f(T1))(f(T2))
        | IntToFloat(T0, T1) -> IntToFloat(f(T0))(f(T1))
        | FloatToInt(T0, T1) -> FloatToInt(f(T0))(f(T1))
        | FloatUnaryIntrinsic(T0, T1, s0) -> FloatUnaryIntrinsic(f(T0))(f(T1))(s0)
        | CallLibm(T0, s0, L0) -> CallLibm(f(T0))(s0)(Ashes.Collection.List.map(f)(L0))
        | BigIntFromInt(T0, T1, b0) -> BigIntFromInt(f(T0))(f(T1))(b0)
        | BigIntToString(T0, T1, b0) -> BigIntToString(f(T0))(f(T1))(b0)
        | BigIntToInt(T0, T1, b0) -> BigIntToInt(f(T0))(f(T1))(b0)
        | BigIntFromString(T0, T1, b0) -> BigIntFromString(f(T0))(f(T1))(b0)
        | BigIntBinary(T0, T1, T2, s0, b0) -> BigIntBinary(f(T0))(f(T1))(f(T2))(s0)(b0)
        | BigIntCompare(T0, T1, T2) -> BigIntCompare(f(T0))(f(T1))(f(T2))
        | CmpStrEq(T0, T1, T2) -> CmpStrEq(f(T0))(f(T1))(f(T2))
        | CmpStrNe(T0, T1, T2) -> CmpStrNe(f(T0))(f(T1))(f(T2))
        | ConcatStr(T0, T1, T2, b0) -> ConcatStr(f(T0))(f(T1))(f(T2))(b0)
        | ConcatStrTip(T0, T1, T2, l0, l1, b0) -> ConcatStrTip(f(T0))(f(T1))(f(T2))(l0)(l1)(b0)
        | ConcatStrN(T0, L0, b0) -> ConcatStrN(f(T0))(Ashes.Collection.List.map(f)(L0))(b0)
        | RegexCompile(T0, T1) -> RegexCompile(f(T0))(f(T1))
        | RegexCompileError(T0, T1) -> RegexCompileError(f(T0))(f(T1))
        | RegexFind(T0, T1, T2, T3) -> RegexFind(f(T0))(f(T1))(f(T2))(f(T3))
        | RegexCaptures(T0, T1, T2, T3) -> RegexCaptures(f(T0))(f(T1))(f(T2))(f(T3))
        | RegexSubstitute(T0, T1, T2, T3) -> RegexSubstitute(f(T0))(f(T1))(f(T2))(f(T3))
        | MakeClosure(T0, s0, T1, n0, b0, b1, b2) -> MakeClosure(f(T0))(s0)(f(T1))(n0)(b0)(b1)(b2)
        | MakeClosureStack(T0, s0, T1, n0, b0, b1) -> MakeClosureStack(f(T0))(s0)(f(T1))(n0)(b0)(b1)
        | LoadFuncAddr(T0, s0) -> LoadFuncAddr(f(T0))(s0)
        | CallClosure(T0, T1, T2, T3) -> CallClosure(f(T0))(f(T1))(f(T2))(f(T3))
        | CallKnown(T0, s0, T1, T2, T3, b0) -> CallKnown(f(T0))(s0)(f(T1))(f(T2))(f(T3))(b0)
        | LoadArgumentOwnership(T0) -> LoadArgumentOwnership(f(T0))
        | Alloc(T0, n0, b0) -> Alloc(f(T0))(n0)(b0)
        | AllocStack(T0, n0) -> AllocStack(f(T0))(n0)
        | AllocAdt(T0, n0, n1, b0, b1) -> AllocAdt(f(T0))(n0)(n1)(b0)(b1)
        | AllocAdtStack(T0, n0, n1, b0) -> AllocAdtStack(f(T0))(n0)(n1)(b0)
        | AllocAdtToSpace(T0, n0, n1, b0) -> AllocAdtToSpace(f(T0))(n0)(n1)(b0)
        | DropReuse(T0, T1, n0, b0) -> DropReuse(f(T0))(f(T1))(n0)(b0)
        | AllocReusing(T0, n0, n1, T1, b0, b1, b2) -> AllocReusing(f(T0))(n0)(n1)(f(T1))(b0)(b1)(b2)
        | SetAdtField(T0, n0, T1, b0) -> SetAdtField(f(T0))(n0)(f(T1))(b0)
        | SaveStackPointer(l0) -> SaveStackPointer(l0)
        | RestoreStackPointer(l0) -> RestoreStackPointer(l0)
        | GetAdtTag(T0, T1) -> GetAdtTag(f(T0))(f(T1))
        | GetAdtField(T0, T1, n0, b0) -> GetAdtField(f(T0))(f(T1))(n0)(b0)
        | PrintInt(T0) -> PrintInt(f(T0))
        | PrintStr(T0) -> PrintStr(f(T0))
        | PrintBool(T0) -> PrintBool(f(T0))
        | WriteStr(T0) -> WriteStr(f(T0))
        | WriteErrorStr(T0, b0) -> WriteErrorStr(f(T0))(b0)
        | ExitProcess(T0) -> ExitProcess(f(T0))
        | WriteBufferedStr(T0, b0) -> WriteBufferedStr(f(T0))(b0)
        | FlushStdout -> FlushStdout
        | ReadLine(T0) -> ReadLine(f(T0))
        | ReadExact(T0, T1) -> ReadExact(f(T0))(f(T1))
        | ConsoleEnableRaw(T0) -> ConsoleEnableRaw(f(T0))
        | ConsoleRestore(T0) -> ConsoleRestore(f(T0))
        | ConsolePoll(T0, T1) -> ConsolePoll(f(T0))(f(T1))
        | MonotonicMillis(T0) -> MonotonicMillis(f(T0))
        | TextByteLength(T0, T1) -> TextByteLength(f(T0))(f(T1))
        | FileReadText(T0, T1) -> FileReadText(f(T0))(f(T1))
        | FileReadAllBytes(T0, T1) -> FileReadAllBytes(f(T0))(f(T1))
        | FileMmap(T0, T1) -> FileMmap(f(T0))(f(T1))
        | FileWriteText(T0, T1, T2) -> FileWriteText(f(T0))(f(T1))(f(T2))
        | FileExists(T0, T1) -> FileExists(f(T0))(f(T1))
        | FileReplace(T0, T1, T2) -> FileReplace(f(T0))(f(T1))(f(T2))
        | FileMakeExecutable(T0, T1) -> FileMakeExecutable(f(T0))(f(T1))
        | DirectoryEntries(T0, T1) -> DirectoryEntries(f(T0))(f(T1))
        | DirectoryCreateAll(T0, T1) -> DirectoryCreateAll(f(T0))(f(T1))
        | DirectoryRemoveTree(T0, T1) -> DirectoryRemoveTree(f(T0))(f(T1))
        | EnvironmentDirectory(T0, ed0) -> EnvironmentDirectory(f(T0))(ed0)
        | EnvironmentGet(T0, T1) -> EnvironmentGet(f(T0))(f(T1))
        | FileOpen(T0, T1) -> FileOpen(f(T0))(f(T1))
        | FileReadChunk(T0, T1, T2) -> FileReadChunk(f(T0))(f(T1))(f(T2))
        | FileReadLine(T0, T1) -> FileReadLine(f(T0))(f(T1))
        | FileClose(T0, T1) -> FileClose(f(T0))(f(T1))
        | TextUncons(T0, T1, b0) -> TextUncons(f(T0))(f(T1))(b0)
        | TextUnconsText(T0, T1, b0) -> TextUnconsText(f(T0))(f(T1))(b0)
        | RuneToText(T0, T1, b0) -> RuneToText(f(T0))(f(T1))(b0)
        | RuneFromInt(T0, T1, b0) -> RuneFromInt(f(T0))(f(T1))(b0)
        | TextParseInt(T0, T1, b0) -> TextParseInt(f(T0))(f(T1))(b0)
        | TextParseFloat(T0, T1, b0) -> TextParseFloat(f(T0))(f(T1))(b0)
        | TextFromInt(T0, T1, b0) -> TextFromInt(f(T0))(f(T1))(b0)
        | TextFromFloat(T0, T1, b0) -> TextFromFloat(f(T0))(f(T1))(b0)
        | TextFormatFloat(T0, T1, T2, b0) -> TextFormatFloat(f(T0))(f(T1))(f(T2))(b0)
        | TextToHex(T0, T1, b0) -> TextToHex(f(T0))(f(T1))(b0)
        | TextAsciiCase(T0, T1, b0, b1) -> TextAsciiCase(f(T0))(f(T1))(b0)(b1)
        | HttpGet(T0, T1) -> HttpGet(f(T0))(f(T1))
        | HttpPost(T0, T1, T2) -> HttpPost(f(T0))(f(T1))(f(T2))
        | NetTcpConnect(T0, T1, T2) -> NetTcpConnect(f(T0))(f(T1))(f(T2))
        | NetTcpSend(T0, T1, T2) -> NetTcpSend(f(T0))(f(T1))(f(T2))
        | NetTcpReceive(T0, T1, T2) -> NetTcpReceive(f(T0))(f(T1))(f(T2))
        | NetTcpClose(T0, T1) -> NetTcpClose(f(T0))(f(T1))
        | NetTcpListen(T0, T1) -> NetTcpListen(f(T0))(f(T1))
        | NetTcpAccept(T0, T1) -> NetTcpAccept(f(T0))(f(T1))
        | BytesEmpty(T0, b0) -> BytesEmpty(f(T0))(b0)
        | BytesSingleton(T0, T1, b0) -> BytesSingleton(f(T0))(f(T1))(b0)
        | BytesLength(T0, T1) -> BytesLength(f(T0))(f(T1))
        | BytesGet(T0, T1, T2) -> BytesGet(f(T0))(f(T1))(f(T2))
        | BytesIndexOf(T0, T1, T2, T3) -> BytesIndexOf(f(T0))(f(T1))(f(T2))(f(T3))
        | BytesCompare(T0, T1, T2) -> BytesCompare(f(T0))(f(T1))(f(T2))
        | BytesScanHash(T0, T1, T2, T3) -> BytesScanHash(f(T0))(f(T1))(f(T2))(f(T3))
        | BytesSubText(T0, T1, T2, T3, b0) -> BytesSubText(f(T0))(f(T1))(f(T2))(f(T3))(b0)
        | BytesSubView(T0, T1, T2, T3) -> BytesSubView(f(T0))(f(T1))(f(T2))(f(T3))
        | BytesAppend(T0, T1, T2, b0) -> BytesAppend(f(T0))(f(T1))(f(T2))(b0)
        | BytesAppendByte(T0, T1, T2, b0) -> BytesAppendByte(f(T0))(f(T1))(f(T2))(b0)
        | BytesAllocate(T0, T1, b0) -> BytesAllocate(f(T0))(f(T1))(b0)
        | BytesCopyRange(T0, T1, T2, T3, T4, T5, b0, b1) -> BytesCopyRange(f(T0))(f(T1))(f(T2))(f(T3))(f(T4))(f(T5))(b0)(b1)
        | BytesSet(T0, T1, T2, T3, b0, b1) -> BytesSet(f(T0))(f(T1))(f(T2))(f(T3))(b0)(b1)
        | BytesSetU16Le(T0, T1, T2, T3, b0, b1) -> BytesSetU16Le(f(T0))(f(T1))(f(T2))(f(T3))(b0)(b1)
        | BytesSetU32Le(T0, T1, T2, T3, b0, b1) -> BytesSetU32Le(f(T0))(f(T1))(f(T2))(f(T3))(b0)(b1)
        | BytesSetU64Le(T0, T1, T2, T3, b0, b1) -> BytesSetU64Le(f(T0))(f(T1))(f(T2))(f(T3))(b0)(b1)
        | BytesFromList(T0, T1, b0) -> BytesFromList(f(T0))(f(T1))(b0)
        | BytesHash(T0, T1) -> BytesHash(f(T0))(f(T1))
        | BytesU16Le(T0, T1, b0) -> BytesU16Le(f(T0))(f(T1))(b0)
        | BytesU32Le(T0, T1, b0) -> BytesU32Le(f(T0))(f(T1))(b0)
        | BytesU64Le(T0, T1, b0) -> BytesU64Le(f(T0))(f(T1))(b0)
        | BytesGetU16Le(T0, T1, T2) -> BytesGetU16Le(f(T0))(f(T1))(f(T2))
        | BytesGetU32Le(T0, T1, T2) -> BytesGetU32Le(f(T0))(f(T1))(f(T2))
        | BytesGetU64Le(T0, T1, T2) -> BytesGetU64Le(f(T0))(f(T1))(f(T2))
        | FileWriteBytes(T0, T1, T2) -> FileWriteBytes(f(T0))(f(T1))(f(T2))
        | SpawnProcess(T0, T1, T2) -> SpawnProcess(f(T0))(f(T1))(f(T2))
        | ProcessWriteStdin(T0, T1, T2) -> ProcessWriteStdin(f(T0))(f(T1))(f(T2))
        | ProcessReadStdoutLine(T0, T1) -> ProcessReadStdoutLine(f(T0))(f(T1))
        | ProcessReadStderrLine(T0, T1) -> ProcessReadStderrLine(f(T0))(f(T1))
        | ProcessWaitForExit(T0, T1) -> ProcessWaitForExit(f(T0))(f(T1))
        | ProcessKill(T0, T1) -> ProcessKill(f(T0))(f(T1))
        | CleanupResource(T0, s0, MA0) -> CleanupResource(f(T0))(s0)(MA0)
        | RcDrop(T0, s0, l0, b0, b1, MS0) -> RcDrop(f(T0))(s0)(l0)(b0)(b1)(MS0)
        | RcDup(T0, T1, b0, b1) -> RcDup(f(T0))(f(T1))(b0)(b1)
        | RcIsUnique(T0, T1) -> RcIsUnique(f(T0))(f(T1))
        | Borrow(T0, T1) -> Borrow(f(T0))(f(T1))
        | TcoResetPending(n0, L0, LL0) -> TcoResetPending(n0)(Ashes.Collection.List.map(f)(L0))(LL0)
        | SaveArenaState(l0, l1, b0) -> SaveArenaState(l0)(l1)(b0)
        | RestoreArenaState(l0, l1, l2, b0) -> RestoreArenaState(l0)(l1)(l2)(b0)
        | ReclaimArenaChunks(l0, l1, b0) -> ReclaimArenaChunks(l0)(l1)(b0)
        | CopyOutArena(T0, T1, n0, b0, cp0, MT0) -> CopyOutArena(f(T0))(f(T1))(n0)(b0)(cp0)(MT0)
        | CopyOutArenaToSpace(T0, T1, n0) -> CopyOutArenaToSpace(f(T0))(f(T1))(n0)
        | CopyFixedInto(T0, T1, n0) -> CopyFixedInto(f(T0))(f(T1))(n0)
        | CopyStringIntoOrFresh(T0, T1, T2) -> CopyStringIntoOrFresh(f(T0))(f(T1))(f(T2))
        | CopyFixedIntoOrFresh(T0, T1, T2, n0) -> CopyFixedIntoOrFresh(f(T0))(f(T1))(f(T2))(n0)
        | CopyOutList(T0, T1, hc0, b0, cp0) -> CopyOutList(f(T0))(f(T1))(hc0)(b0)(cp0)
        | CopyOutClosure(T0, T1, b0, cp0) -> CopyOutClosure(f(T0))(f(T1))(b0)(cp0)
        | CopyOutTcoListCell(T0, T1, hc0, cp0) -> CopyOutTcoListCell(f(T0))(f(T1))(hc0)(cp0)
        | ToCString(T0, T1) -> ToCString(f(T0))(f(T1))
        | AllocFfiOut(T0, ea0) -> AllocFfiOut(f(T0))(ea0)
        | LoadFfiOut(T0, T1, ea0) -> LoadFfiOut(f(T0))(f(T1))(ea0)
        | CopyFfiString(T0, T1, ea0) -> CopyFfiString(f(T0))(f(T1))(ea0)
        | CopyFfiBytes(T0, T1, T2) -> CopyFfiBytes(f(T0))(f(T1))(f(T2))
        | CallExternal(T0, s0, MS0, L0, EA0, ea0) -> CallExternal(f(T0))(s0)(MS0)(Ashes.Collection.List.map(f)(L0))(EA0)(ea0)
        | CreateTask(T0, T1, n0, n1, MS0, b0) -> CreateTask(f(T0))(f(T1))(n0)(n1)(MS0)(b0)
        | CreateCompletedTask(T0, T1) -> CreateCompletedTask(f(T0))(f(T1))
        | AwaitTask(T0, T1) -> AwaitTask(f(T0))(f(T1))
        | RunTask(T0, T1) -> RunTask(f(T0))(f(T1))
        | SpawnTask(T0, T1) -> SpawnTask(f(T0))(f(T1))
        | CreateTaskScope(T0, b0) -> CreateTaskScope(f(T0))(b0)
        | CreateScopedTask(T0, T1, T2) -> CreateScopedTask(f(T0))(f(T1))(f(T2))
        | ForkScopedTask(T0, T1, T2) -> ForkScopedTask(f(T0))(f(T1))(f(T2))
        | JoinScopedTask(T0, T1) -> JoinScopedTask(f(T0))(f(T1))
        | ParallelFork(T0, T1) -> ParallelFork(f(T0))(f(T1))
        | ParallelJoin(T0, T1) -> ParallelJoin(f(T0))(f(T1))
        | ParallelCleanup(T0) -> ParallelCleanup(f(T0))
        | LoadParallelWorkerOverride(T0) -> LoadParallelWorkerOverride(f(T0))
        | StoreParallelWorkerOverride(T0) -> StoreParallelWorkerOverride(f(T0))
        | ParallelQueueStart(T0, T1, T2, T3) -> ParallelQueueStart(f(T0))(f(T1))(f(T2))(f(T3))
        | ParallelQueueAwait(T0, T1) -> ParallelQueueAwait(f(T0))(f(T1))
        | ParallelQueueCleanup(T0) -> ParallelQueueCleanup(f(T0))
        | Suspend(T0, n0, T1, FS0) -> Suspend(f(T0))(n0)(f(T1))(mapFrameSaveTemps(f)(FS0))
        | Resume(T0, T1, FR0) -> Resume(f(T0))(f(T1))(mapFrameRestoreTemps(f)(FR0))
        | AsyncSleep(T0, T1) -> AsyncSleep(f(T0))(f(T1))
        | CreateTcpConnectTask(T0, T1, T2) -> CreateTcpConnectTask(f(T0))(f(T1))(f(T2))
        | CreateTcpSendTask(T0, T1, T2) -> CreateTcpSendTask(f(T0))(f(T1))(f(T2))
        | CreateTcpReceiveTask(T0, T1, T2) -> CreateTcpReceiveTask(f(T0))(f(T1))(f(T2))
        | CreateTcpCloseTask(T0, T1) -> CreateTcpCloseTask(f(T0))(f(T1))
        | CreateTcpListenTask(T0, T1) -> CreateTcpListenTask(f(T0))(f(T1))
        | CreateForkWorkersTask(T0, T1, T2) -> CreateForkWorkersTask(f(T0))(f(T1))(f(T2))
        | SetDrainTimeout(T0, T1) -> SetDrainTimeout(f(T0))(f(T1))
        | RequestServerStop(T0) -> RequestServerStop(f(T0))
        | CreateTcpAcceptTask(T0, T1) -> CreateTcpAcceptTask(f(T0))(f(T1))
        | CreateHttpGetTask(T0, T1) -> CreateHttpGetTask(f(T0))(f(T1))
        | CreateHttpPostTask(T0, T1, T2) -> CreateHttpPostTask(f(T0))(f(T1))(f(T2))
        | CreateTlsConnectTask(T0, T1, T2) -> CreateTlsConnectTask(f(T0))(f(T1))(f(T2))
        | CreateTlsHandshakeTask(T0, T1, T2) -> CreateTlsHandshakeTask(f(T0))(f(T1))(f(T2))
        | CreateTlsServerHandshakeTask(T0, T1, T2, T3) -> CreateTlsServerHandshakeTask(f(T0))(f(T1))(f(T2))(f(T3))
        | CreateTlsSendTask(T0, T1, T2) -> CreateTlsSendTask(f(T0))(f(T1))(f(T2))
        | CreateTlsReceiveTask(T0, T1, T2) -> CreateTlsReceiveTask(f(T0))(f(T1))(f(T2))
        | CreateTlsCloseTask(T0, T1) -> CreateTlsCloseTask(f(T0))(f(T1))
        | AsyncAll(T0, T1) -> AsyncAll(f(T0))(f(T1))
        | AsyncRace(T0, T1) -> AsyncRace(f(T0))(f(T1))
        | PanicStr(T0) -> PanicStr(f(T0))
        | LoadCapabilityHandler(T0, n0) -> LoadCapabilityHandler(f(T0))(n0)
        | StoreCapabilityHandler(n0, T0) -> StoreCapabilityHandler(n0)(f(T0))
        | Label(s0) -> Label(s0)
        | Jump(s0) -> Jump(s0)
        | JumpIfFalse(T0, s0) -> JumpIfFalse(f(T0))(s0)
        | SwitchTag(T0, SC0, s0) -> SwitchTag(f(T0))(SC0)(s0)
        | Return(T0) -> Return(f(T0))

// `mapInstructionLocals` rewrites every local slot operand of one instruction, the arms
// covering exactly the constructors that carry an `IrLocal` (an owner slot of -1 passes through
// `f` like any other value, so `f` decides what a missing owner maps to); every other kind is
// carried unchanged. A loop retiring an unused flag slot renumbers the function's locals through
// it.
let mapInstructionLocals f (kind: IrInstructionKind) =
    match kind with
        | LoadLocal(T0, l0) -> LoadLocal(T0)(f(l0))
        | StoreLocal(l0, T0) -> StoreLocal(f(l0))(T0)
        | ConcatStrTip(T0, T1, T2, l0, l1, b0) -> ConcatStrTip(T0)(T1)(T2)(f(l0))(f(l1))(b0)
        | SaveStackPointer(l0) -> SaveStackPointer(f(l0))
        | RestoreStackPointer(l0) -> RestoreStackPointer(f(l0))
        | RcDrop(T0, s0, l0, b0, b1, m0) -> RcDrop(T0)(s0)(f(l0))(b0)(b1)(m0)
        | TcoResetPending(n0, Ts0, Ls0) -> TcoResetPending(n0)(Ts0)(map(f)(Ls0))
        | SaveArenaState(l0, l1, b0) -> SaveArenaState(f(l0))(f(l1))(b0)
        | RestoreArenaState(l0, l1, l2, b0) -> RestoreArenaState(f(l0))(f(l1))(f(l2))(b0)
        | ReclaimArenaChunks(l0, l1, b0) -> ReclaimArenaChunks(f(l0))(f(l1))(b0)
        | other -> other
