// <auto-generated />
using System;
using Ashes.Registry.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ashes.Registry.Storage.Migrations
{
    [DbContext(typeof(RegistryDbContext))]
    [Migration("20260707171721_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Ashes.Registry.Storage.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Ashes.Registry.Storage.ApiTokenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HashedSecret")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Ashes.Registry.Storage.PackageEntity", b =>
                {
                    b.Property<string>("Namespace")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Downloads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Namespace");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Ashes.Registry.Storage.PackageOwnerEntity", b =>
                {
                    b.Property<string>("PackageNamespace")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("PackageNamespace", "AccountId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Ashes.Registry.Storage.PackageVersionEntity", b =>
                {
                    b.Property<string>("Namespace")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DependenciesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Yanked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Namespace", "Version");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("Ashes.Registry.Storage.PackageOwnerEntity", b =>
                {
                    b.HasOne("Ashes.Registry.Storage.PackageEntity", null)
                        .WithMany("Owners")
                        .HasForeignKey("PackageNamespace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashes.Registry.Storage.PackageVersionEntity", b =>
                {
                    b.HasOne("Ashes.Registry.Storage.PackageEntity", null)
                        .WithMany("Versions")
                        .HasForeignKey("Namespace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashes.Registry.Storage.PackageEntity", b =>
                {
                    b.Navigation("Owners");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
