using System.Text;
using Microsoft.CodeAnalysis;

namespace DocsApiGen;

/// <summary>Renders one project's public API surface to a Markdown page.</summary>
internal static class MarkdownPage
{
    private const string GitHubBlobBaseUrl = "https://github.com/MattiasHognas/Ashes/blob/main/";

    private static readonly SymbolDisplayFormat TypeNameFormat = SymbolDisplayFormat.MinimallyQualifiedFormat;

    private static readonly SymbolDisplayFormat MemberSignatureFormat = new(
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        memberOptions: SymbolDisplayMemberOptions.IncludeParameters | SymbolDisplayMemberOptions.IncludeType,
        parameterOptions: SymbolDisplayParameterOptions.IncludeType
            | SymbolDisplayParameterOptions.IncludeName
            | SymbolDisplayParameterOptions.IncludeDefaultValue
            | SymbolDisplayParameterOptions.IncludeParamsRefOut,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes
            | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private readonly record struct MemberRow(string Name, string Signature, string Summary);

    internal static string Render(ProjectSpec project, IReadOnlyList<INamedTypeSymbol> types, string repoRoot)
    {
        List<INamedTypeSymbol> sorted = [.. types.OrderBy(QualifiedTypeName, StringComparer.Ordinal)];

        StringBuilder builder = new();
        AppendHeader(builder, project);
        AppendOverviewTable(builder, sorted, repoRoot);
        AppendPrimaryTypeSections(builder, project, sorted);
        return builder.ToString();
    }

    private static void AppendHeader(StringBuilder builder, ProjectSpec project)
    {
        builder.Append("# ").Append(project.DisplayName).Append(" API Reference\n\n");
        builder.Append("Generated from the `///` XML doc comments in `src/").Append(project.DirectoryName)
            .Append("/`. See the [Compilation Pipeline](../architecture.md#compilation-pipeline) for how this ")
            .Append("project fits into the compiler. This page is regenerated by `tools/docs-api-gen` on every ")
            .Append("docs build — edit the doc comments in the source, not this file.\n\n");
    }

    private static void AppendOverviewTable(StringBuilder builder, IReadOnlyList<INamedTypeSymbol> types, string repoRoot)
    {
        builder.Append("## Types\n\n");
        builder.Append("| Type | Kind | Summary | Source |\n");
        builder.Append("|------|------|---------|--------|\n");

        foreach (INamedTypeSymbol type in types)
        {
            string name = QualifiedTypeName(type);
            string kind = DescribeKind(type);
            string summary = FirstSentence(DocComment.ResolveSummary(type));
            string source = FormatSourceLink(type, repoRoot);
            builder.Append("| `").Append(EscapeCell(name)).Append('`')
                .Append(" | ").Append(kind)
                .Append(" | ").Append(EscapeCell(summary))
                .Append(" | ").Append(source)
                .Append(" |\n");
        }

        builder.Append('\n');
    }

    private static void AppendPrimaryTypeSections(StringBuilder builder, ProjectSpec project, IReadOnlyList<INamedTypeSymbol> types)
    {
        foreach (string primaryName in project.PrimaryTypeNames)
        {
            INamedTypeSymbol? type = types.FirstOrDefault(t => string.Equals(t.Name, primaryName, StringComparison.Ordinal));
            if (type is not null)
            {
                AppendPrimaryTypeSection(builder, type);
            }
        }
    }

    private static void AppendPrimaryTypeSection(StringBuilder builder, INamedTypeSymbol type)
    {
        builder.Append("## ").Append(QualifiedTypeName(type)).Append("\n\n");

        string summary = DocComment.ResolveSummary(type);
        if (summary.Length > 0)
        {
            builder.Append(summary).Append("\n\n");
        }

        List<MemberRow> rows = CollectMemberRows(type);
        if (rows.Count == 0)
        {
            return;
        }

        builder.Append("| Member | Signature | Summary |\n");
        builder.Append("|--------|-----------|---------|\n");
        foreach (MemberRow row in rows)
        {
            builder.Append("| `").Append(EscapeCell(row.Name)).Append('`')
                .Append(" | `").Append(EscapeCell(row.Signature)).Append('`')
                .Append(" | ").Append(EscapeCell(row.Summary))
                .Append(" |\n");
        }

        builder.Append('\n');
    }

    private static List<MemberRow> CollectMemberRows(INamedTypeSymbol type)
    {
        List<MemberRow> rows = [];

        // Positional record parameters: their docs live on the type's own <param> tags, not on
        // the synthesized property symbol, so extract them separately from regular members.
        HashSet<string> paramNames = new(StringComparer.Ordinal);
        foreach ((string paramName, string paramText) in DocComment.ExtractParams(type))
        {
            IParameterSymbol? parameter = FindPrimaryConstructorParameter(type, paramName);
            string signature = parameter is null ? paramName : parameter.Type.ToDisplayString(TypeNameFormat);
            rows.Add(new MemberRow(paramName, signature, paramText));
            paramNames.Add(paramName);
        }

        // Not deduplicated by name here: overloaded methods (e.g. multiple `Format(...)`
        // overloads) share a name but must each get their own row.
        foreach (ISymbol member in type.GetMembers().OrderBy(m => m.Name, StringComparer.Ordinal))
        {
            if (!IsDocumentableMember(member) || paramNames.Contains(member.Name))
            {
                continue;
            }

            string summary = DocComment.ResolveSummary(member);
            if (summary.Length > 0)
            {
                rows.Add(new MemberRow(member.Name, member.ToDisplayString(MemberSignatureFormat), summary));
            }
        }

        return rows;
    }

    private static IParameterSymbol? FindPrimaryConstructorParameter(INamedTypeSymbol type, string paramName)
    {
        foreach (IMethodSymbol constructor in type.Constructors)
        {
            foreach (IParameterSymbol parameter in constructor.Parameters)
            {
                if (string.Equals(parameter.Name, paramName, StringComparison.Ordinal))
                {
                    return parameter;
                }
            }
        }

        return null;
    }

    private static bool IsDocumentableMember(ISymbol member)
    {
        if (member.DeclaredAccessibility != Accessibility.Public || member.IsImplicitlyDeclared)
        {
            return false;
        }

        return member switch
        {
            IMethodSymbol { MethodKind: MethodKind.Ordinary } => true,
            IPropertySymbol => true,
            IFieldSymbol => true,
            IEventSymbol => true,
            _ => false,
        };
    }

    // SymbolDisplayFormat.MinimallyQualifiedFormat does not prepend containing types for a bare
    // ToDisplayString() call, so a nested case type like IrInst.Borrow would render as just
    // "Borrow". Qualify explicitly so nested types stay identifiable in a flat, sorted table.
    private static string QualifiedTypeName(INamedTypeSymbol type)
    {
        List<string> parts = [];
        for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType)
        {
            parts.Insert(0, current.Name);
        }

        return string.Join('.', parts);
    }

    private static string DescribeKind(INamedTypeSymbol type)
    {
        return type.TypeKind switch
        {
            TypeKind.Interface => "interface",
            TypeKind.Enum => "enum",
            TypeKind.Delegate => "delegate",
            TypeKind.Struct when type.IsRecord => "record struct",
            TypeKind.Struct => "struct",
            TypeKind.Class when type.IsRecord => "record",
            TypeKind.Class => "class",
            _ => type.TypeKind.ToString().ToLowerInvariant(),
        };
    }

    private static string FirstSentence(string text)
    {
        if (text.Length == 0)
        {
            return string.Empty;
        }

        int periodIndex = text.IndexOf(". ", StringComparison.Ordinal);
        return periodIndex >= 0 ? text[..(periodIndex + 1)] : text;
    }

    private static string FormatSourceLink(ISymbol symbol, string repoRoot)
    {
        Location? location = symbol.Locations.FirstOrDefault(l => l.IsInSource);
        if (location is null)
        {
            return string.Empty;
        }

        FileLinePositionSpan span = location.GetLineSpan();
        string relativePath = Path.GetRelativePath(repoRoot, span.Path).Replace(Path.DirectorySeparatorChar, '/');
        int line = span.StartLinePosition.Line + 1;
        return $"[source]({GitHubBlobBaseUrl}{relativePath}#L{line})";
    }

    private static string EscapeCell(string text)
    {
        string collapsed = string.Join(' ', text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
        return collapsed.Replace("|", "\\|", StringComparison.Ordinal);
    }
}
