#!/usr/bin/env node
// Mock compiler for integration tests.
// Handles --version and common compiler subcommands.
const command = process.argv[2];

switch (command) {
    case '--version':
        console.log('0.0.1');
        process.exit(0);
    case 'compile':
        console.log('Compiled successfully');
        process.exit(0);
    case 'run':
        console.log('Running...');
        process.exit(0);
    case 'test':
        console.log('All tests passed');
        process.exit(0);
    default:
        process.exit(0);
}
